print("Hello WorldðŸ˜‰ðŸ˜‰ðŸ˜‰")

# Error handling
try:
    print(x/2)
except Exception as e:
    print(f"We couldn't do this because of {e}")

# Practice:
try:
    print(y)
except Exception as e:
    print(f"Couldn't be executed because of {e}")

# Practice:
try:
    if 3==3:
        print(f = 3)
except Exception as e:
    print(f"Couldn't executed because of {e}")

# <<<---Error Handling--->>>